exclude: "\
    ^(\
    .github|\
    .changes|\
    botocore/data|\
    botocore/vendored|\
    botocore/compat.py|\
    docs/|\
    tests/unit/auth/aws4_testsuite|\
    tests/unit/response_parsing/xml\
    )"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
