language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
sudo: false
install:
  - python scripts/ci/install
script: python scripts/ci/run-tests
after_success:
  - pip install python-coveralls && cd tests && coveralls
