language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2==0.5.1; pip install --use-mirrors -r requirements26.txt; fi
  - pip install -r requirements.txt
  - pip install coverage python-coveralls
script: nosetests tests/unit --cover-erase --with-coverage --cover-package botocore
after_success: coveralls
